// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package bootstrap

import (
	"github.com/stainour/test10/api"
	"github.com/stainour/test10/domain"
	"github.com/stainour/test10/infrastructure"
)

// Injectors from wire.go:

func InitializeService() (api.UrlShortenerServer, error) {
	mongoConnectionSetting := NewMongoConnectionSetting()
	sequenceGenerator, err := infrastructure.NewMongoSequenceGenerator(mongoConnectionSetting)
	if err != nil {
		return nil, err
	}
	urlMappingRepository, err := infrastructure.NewMongoUrlMappingRepository(mongoConnectionSetting)
	if err != nil {
		return nil, err
	}
	apiService := domain.NewApiService(sequenceGenerator, urlMappingRepository)
	urlShortenerServer := api.NewServer(apiService)
	return urlShortenerServer, nil
}

// wire.go:

func NewMongoConnectionSetting() infrastructure.MongoConnectionSetting {
	return *infrastructure.NewMongoConnectionSetting("mongodb://localhost:27017", "urlShortener")
}
