// Code generated by protoc-gen-go. DO NOT EDIT.
// source: urlShortener.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreationResult_Status int32

const (
	CreationResult_OK       CreationResult_Status = 0
	CreationResult_CONFLICT CreationResult_Status = 1
	CreationResult_ERROR    CreationResult_Status = 2
)

var CreationResult_Status_name = map[int32]string{
	0: "OK",
	1: "CONFLICT",
	2: "ERROR",
}

var CreationResult_Status_value = map[string]int32{
	"OK":       0,
	"CONFLICT": 1,
	"ERROR":    2,
}

func (x CreationResult_Status) String() string {
	return proto.EnumName(CreationResult_Status_name, int32(x))
}

func (CreationResult_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3b448ccde980264e, []int{2, 0}
}

type UrlKeyStat struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	HitCount             int64    `protobuf:"varint,2,opt,name=HitCount,proto3" json:"HitCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UrlKeyStat) Reset()         { *m = UrlKeyStat{} }
func (m *UrlKeyStat) String() string { return proto.CompactTextString(m) }
func (*UrlKeyStat) ProtoMessage()    {}
func (*UrlKeyStat) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b448ccde980264e, []int{0}
}

func (m *UrlKeyStat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UrlKeyStat.Unmarshal(m, b)
}
func (m *UrlKeyStat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UrlKeyStat.Marshal(b, m, deterministic)
}
func (m *UrlKeyStat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UrlKeyStat.Merge(m, src)
}
func (m *UrlKeyStat) XXX_Size() int {
	return xxx_messageInfo_UrlKeyStat.Size(m)
}
func (m *UrlKeyStat) XXX_DiscardUnknown() {
	xxx_messageInfo_UrlKeyStat.DiscardUnknown(m)
}

var xxx_messageInfo_UrlKeyStat proto.InternalMessageInfo

func (m *UrlKeyStat) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *UrlKeyStat) GetHitCount() int64 {
	if m != nil {
		return m.HitCount
	}
	return 0
}

type UrlKeyStats struct {
	Stats                []*UrlKeyStat `protobuf:"bytes,1,rep,name=stats,proto3" json:"stats,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *UrlKeyStats) Reset()         { *m = UrlKeyStats{} }
func (m *UrlKeyStats) String() string { return proto.CompactTextString(m) }
func (*UrlKeyStats) ProtoMessage()    {}
func (*UrlKeyStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b448ccde980264e, []int{1}
}

func (m *UrlKeyStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UrlKeyStats.Unmarshal(m, b)
}
func (m *UrlKeyStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UrlKeyStats.Marshal(b, m, deterministic)
}
func (m *UrlKeyStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UrlKeyStats.Merge(m, src)
}
func (m *UrlKeyStats) XXX_Size() int {
	return xxx_messageInfo_UrlKeyStats.Size(m)
}
func (m *UrlKeyStats) XXX_DiscardUnknown() {
	xxx_messageInfo_UrlKeyStats.DiscardUnknown(m)
}

var xxx_messageInfo_UrlKeyStats proto.InternalMessageInfo

func (m *UrlKeyStats) GetStats() []*UrlKeyStat {
	if m != nil {
		return m.Stats
	}
	return nil
}

type CreationResult struct {
	Status               CreationResult_Status `protobuf:"varint,1,opt,name=status,proto3,enum=CreationResult_Status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *CreationResult) Reset()         { *m = CreationResult{} }
func (m *CreationResult) String() string { return proto.CompactTextString(m) }
func (*CreationResult) ProtoMessage()    {}
func (*CreationResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b448ccde980264e, []int{2}
}

func (m *CreationResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreationResult.Unmarshal(m, b)
}
func (m *CreationResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreationResult.Marshal(b, m, deterministic)
}
func (m *CreationResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreationResult.Merge(m, src)
}
func (m *CreationResult) XXX_Size() int {
	return xxx_messageInfo_CreationResult.Size(m)
}
func (m *CreationResult) XXX_DiscardUnknown() {
	xxx_messageInfo_CreationResult.DiscardUnknown(m)
}

var xxx_messageInfo_CreationResult proto.InternalMessageInfo

func (m *CreationResult) GetStatus() CreationResult_Status {
	if m != nil {
		return m.Status
	}
	return CreationResult_OK
}

type OriginalUrlRequest struct {
	OriginalUrl          string   `protobuf:"bytes,1,opt,name=originalUrl,proto3" json:"originalUrl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OriginalUrlRequest) Reset()         { *m = OriginalUrlRequest{} }
func (m *OriginalUrlRequest) String() string { return proto.CompactTextString(m) }
func (*OriginalUrlRequest) ProtoMessage()    {}
func (*OriginalUrlRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b448ccde980264e, []int{3}
}

func (m *OriginalUrlRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OriginalUrlRequest.Unmarshal(m, b)
}
func (m *OriginalUrlRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OriginalUrlRequest.Marshal(b, m, deterministic)
}
func (m *OriginalUrlRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OriginalUrlRequest.Merge(m, src)
}
func (m *OriginalUrlRequest) XXX_Size() int {
	return xxx_messageInfo_OriginalUrlRequest.Size(m)
}
func (m *OriginalUrlRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OriginalUrlRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OriginalUrlRequest proto.InternalMessageInfo

func (m *OriginalUrlRequest) GetOriginalUrl() string {
	if m != nil {
		return m.OriginalUrl
	}
	return ""
}

type OriginalUrlResponse struct {
	OriginalUrl          string   `protobuf:"bytes,1,opt,name=originalUrl,proto3" json:"originalUrl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OriginalUrlResponse) Reset()         { *m = OriginalUrlResponse{} }
func (m *OriginalUrlResponse) String() string { return proto.CompactTextString(m) }
func (*OriginalUrlResponse) ProtoMessage()    {}
func (*OriginalUrlResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b448ccde980264e, []int{4}
}

func (m *OriginalUrlResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OriginalUrlResponse.Unmarshal(m, b)
}
func (m *OriginalUrlResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OriginalUrlResponse.Marshal(b, m, deterministic)
}
func (m *OriginalUrlResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OriginalUrlResponse.Merge(m, src)
}
func (m *OriginalUrlResponse) XXX_Size() int {
	return xxx_messageInfo_OriginalUrlResponse.Size(m)
}
func (m *OriginalUrlResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OriginalUrlResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OriginalUrlResponse proto.InternalMessageInfo

func (m *OriginalUrlResponse) GetOriginalUrl() string {
	if m != nil {
		return m.OriginalUrl
	}
	return ""
}

type ShortenedlUrlRequest struct {
	ShortenedlUrl        string   `protobuf:"bytes,1,opt,name=shortenedlUrl,proto3" json:"shortenedlUrl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShortenedlUrlRequest) Reset()         { *m = ShortenedlUrlRequest{} }
func (m *ShortenedlUrlRequest) String() string { return proto.CompactTextString(m) }
func (*ShortenedlUrlRequest) ProtoMessage()    {}
func (*ShortenedlUrlRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b448ccde980264e, []int{5}
}

func (m *ShortenedlUrlRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShortenedlUrlRequest.Unmarshal(m, b)
}
func (m *ShortenedlUrlRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShortenedlUrlRequest.Marshal(b, m, deterministic)
}
func (m *ShortenedlUrlRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShortenedlUrlRequest.Merge(m, src)
}
func (m *ShortenedlUrlRequest) XXX_Size() int {
	return xxx_messageInfo_ShortenedlUrlRequest.Size(m)
}
func (m *ShortenedlUrlRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ShortenedlUrlRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ShortenedlUrlRequest proto.InternalMessageInfo

func (m *ShortenedlUrlRequest) GetShortenedlUrl() string {
	if m != nil {
		return m.ShortenedlUrl
	}
	return ""
}

type StatisticRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatisticRequest) Reset()         { *m = StatisticRequest{} }
func (m *StatisticRequest) String() string { return proto.CompactTextString(m) }
func (*StatisticRequest) ProtoMessage()    {}
func (*StatisticRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b448ccde980264e, []int{6}
}

func (m *StatisticRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatisticRequest.Unmarshal(m, b)
}
func (m *StatisticRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatisticRequest.Marshal(b, m, deterministic)
}
func (m *StatisticRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatisticRequest.Merge(m, src)
}
func (m *StatisticRequest) XXX_Size() int {
	return xxx_messageInfo_StatisticRequest.Size(m)
}
func (m *StatisticRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StatisticRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StatisticRequest proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("CreationResult_Status", CreationResult_Status_name, CreationResult_Status_value)
	proto.RegisterType((*UrlKeyStat)(nil), "UrlKeyStat")
	proto.RegisterType((*UrlKeyStats)(nil), "UrlKeyStats")
	proto.RegisterType((*CreationResult)(nil), "CreationResult")
	proto.RegisterType((*OriginalUrlRequest)(nil), "OriginalUrlRequest")
	proto.RegisterType((*OriginalUrlResponse)(nil), "OriginalUrlResponse")
	proto.RegisterType((*ShortenedlUrlRequest)(nil), "ShortenedlUrlRequest")
	proto.RegisterType((*StatisticRequest)(nil), "StatisticRequest")
}

func init() { proto.RegisterFile("urlShortener.proto", fileDescriptor_3b448ccde980264e) }

var fileDescriptor_3b448ccde980264e = []byte{
	// 332 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xcf, 0x4e, 0xfa, 0x40,
	0x10, 0xc7, 0x7f, 0x0b, 0xa1, 0x81, 0x29, 0x3f, 0xac, 0x03, 0x1a, 0xd2, 0x53, 0xdd, 0x78, 0xc0,
	0xcb, 0x86, 0x60, 0xa2, 0x89, 0xd1, 0x53, 0xa3, 0x68, 0x30, 0x36, 0x59, 0xe4, 0x01, 0x50, 0x37,
	0xda, 0xd8, 0x74, 0x71, 0x77, 0x7a, 0xf0, 0xa9, 0x7c, 0x45, 0xd3, 0x52, 0xa1, 0x20, 0x07, 0x6f,
	0xd3, 0xef, 0x9f, 0x4c, 0xe6, 0xd3, 0x05, 0xcc, 0x4c, 0x32, 0x7d, 0xd3, 0x86, 0x54, 0xaa, 0x8c,
	0x58, 0x18, 0x4d, 0x9a, 0x5f, 0x00, 0xcc, 0x4c, 0x32, 0x51, 0x9f, 0x53, 0x9a, 0x13, 0x7a, 0x50,
	0xcf, 0x4c, 0xd2, 0x67, 0x01, 0x1b, 0xb4, 0x64, 0x3e, 0xa2, 0x0f, 0xcd, 0xdb, 0x98, 0x42, 0x9d,
	0xa5, 0xd4, 0xaf, 0x05, 0x6c, 0x50, 0x97, 0xab, 0x6f, 0x3e, 0x04, 0x77, 0xdd, 0xb5, 0x78, 0x04,
	0x0d, 0x9b, 0x0f, 0x7d, 0x16, 0xd4, 0x07, 0xee, 0xc8, 0x15, 0x6b, 0x53, 0x2e, 0x1d, 0xfe, 0x0e,
	0x9d, 0xd0, 0xa8, 0x39, 0xc5, 0x3a, 0x95, 0xca, 0x66, 0x09, 0xa1, 0x00, 0x27, 0xb7, 0x32, 0x5b,
	0x2c, 0xed, 0x8c, 0x0e, 0xc5, 0x66, 0x40, 0x4c, 0x0b, 0x57, 0x96, 0x29, 0x7e, 0x02, 0xce, 0x52,
	0x41, 0x07, 0x6a, 0xd1, 0xc4, 0xfb, 0x87, 0x6d, 0x68, 0x86, 0xd1, 0xc3, 0xcd, 0xfd, 0x5d, 0xf8,
	0xe8, 0x31, 0x6c, 0x41, 0xe3, 0x5a, 0xca, 0x48, 0x7a, 0x35, 0x7e, 0x06, 0x18, 0x99, 0xf8, 0x35,
	0x4e, 0xe7, 0xc9, 0xcc, 0x24, 0x52, 0x7d, 0x64, 0xca, 0x12, 0x06, 0xe0, 0xea, 0xb5, 0x5a, 0x9e,
	0x5a, 0x95, 0xf8, 0x39, 0x74, 0x37, 0x7a, 0x76, 0xa1, 0x53, 0xab, 0xfe, 0x50, 0xbc, 0x84, 0xde,
	0x0f, 0xde, 0x97, 0xea, 0xca, 0x63, 0xf8, 0x6f, 0xab, 0x7a, 0xd9, 0xdd, 0x14, 0x39, 0x82, 0x97,
	0x5f, 0x16, 0x5b, 0x8a, 0x9f, 0xcb, 0xe6, 0xe8, 0x8b, 0x41, 0x7b, 0x56, 0xf9, 0x69, 0x38, 0x84,
	0xf6, 0x58, 0xd1, 0x2a, 0x87, 0xfb, 0x62, 0xbb, 0xe3, 0x57, 0xb9, 0x0f, 0x59, 0x0e, 0xb8, 0x20,
	0xaa, 0xb0, 0x2b, 0x7e, 0xe3, 0xf0, 0xf7, 0xb6, 0x78, 0xe3, 0x15, 0x74, 0xc6, 0x8a, 0x2a, 0x49,
	0x3c, 0x10, 0xbb, 0xae, 0xf2, 0x7b, 0x62, 0x07, 0xa5, 0x27, 0xa7, 0x78, 0x56, 0xa7, 0xdf, 0x01,
	0x00, 0x00, 0xff, 0xff, 0xc9, 0x96, 0xdb, 0x4a, 0x6c, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UrlShortenerClient is the client API for UrlShortener service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UrlShortenerClient interface {
	GetStatistic(ctx context.Context, in *StatisticRequest, opts ...grpc.CallOption) (UrlShortener_GetStatisticClient, error)
	Create(ctx context.Context, in *OriginalUrlRequest, opts ...grpc.CallOption) (*CreationResult, error)
	GetOriginalUrl(ctx context.Context, in *ShortenedlUrlRequest, opts ...grpc.CallOption) (*OriginalUrlResponse, error)
}

type urlShortenerClient struct {
	cc *grpc.ClientConn
}

func NewUrlShortenerClient(cc *grpc.ClientConn) UrlShortenerClient {
	return &urlShortenerClient{cc}
}

func (c *urlShortenerClient) GetStatistic(ctx context.Context, in *StatisticRequest, opts ...grpc.CallOption) (UrlShortener_GetStatisticClient, error) {
	stream, err := c.cc.NewStream(ctx, &_UrlShortener_serviceDesc.Streams[0], "/UrlShortener/GetStatistic", opts...)
	if err != nil {
		return nil, err
	}
	x := &urlShortenerGetStatisticClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type UrlShortener_GetStatisticClient interface {
	Recv() (*UrlKeyStat, error)
	grpc.ClientStream
}

type urlShortenerGetStatisticClient struct {
	grpc.ClientStream
}

func (x *urlShortenerGetStatisticClient) Recv() (*UrlKeyStat, error) {
	m := new(UrlKeyStat)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *urlShortenerClient) Create(ctx context.Context, in *OriginalUrlRequest, opts ...grpc.CallOption) (*CreationResult, error) {
	out := new(CreationResult)
	err := c.cc.Invoke(ctx, "/UrlShortener/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *urlShortenerClient) GetOriginalUrl(ctx context.Context, in *ShortenedlUrlRequest, opts ...grpc.CallOption) (*OriginalUrlResponse, error) {
	out := new(OriginalUrlResponse)
	err := c.cc.Invoke(ctx, "/UrlShortener/GetOriginalUrl", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UrlShortenerServer is the server API for UrlShortener service.
type UrlShortenerServer interface {
	GetStatistic(*StatisticRequest, UrlShortener_GetStatisticServer) error
	Create(context.Context, *OriginalUrlRequest) (*CreationResult, error)
	GetOriginalUrl(context.Context, *ShortenedlUrlRequest) (*OriginalUrlResponse, error)
}

// UnimplementedUrlShortenerServer can be embedded to have forward compatible implementations.
type UnimplementedUrlShortenerServer struct {
}

func (*UnimplementedUrlShortenerServer) GetStatistic(req *StatisticRequest, srv UrlShortener_GetStatisticServer) error {
	return status.Errorf(codes.Unimplemented, "method GetStatistic not implemented")
}
func (*UnimplementedUrlShortenerServer) Create(ctx context.Context, req *OriginalUrlRequest) (*CreationResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedUrlShortenerServer) GetOriginalUrl(ctx context.Context, req *ShortenedlUrlRequest) (*OriginalUrlResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOriginalUrl not implemented")
}

func RegisterUrlShortenerServer(s *grpc.Server, srv UrlShortenerServer) {
	s.RegisterService(&_UrlShortener_serviceDesc, srv)
}

func _UrlShortener_GetStatistic_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StatisticRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(UrlShortenerServer).GetStatistic(m, &urlShortenerGetStatisticServer{stream})
}

type UrlShortener_GetStatisticServer interface {
	Send(*UrlKeyStat) error
	grpc.ServerStream
}

type urlShortenerGetStatisticServer struct {
	grpc.ServerStream
}

func (x *urlShortenerGetStatisticServer) Send(m *UrlKeyStat) error {
	return x.ServerStream.SendMsg(m)
}

func _UrlShortener_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OriginalUrlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UrlShortenerServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/UrlShortener/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UrlShortenerServer).Create(ctx, req.(*OriginalUrlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UrlShortener_GetOriginalUrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShortenedlUrlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UrlShortenerServer).GetOriginalUrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/UrlShortener/GetOriginalUrl",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UrlShortenerServer).GetOriginalUrl(ctx, req.(*ShortenedlUrlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UrlShortener_serviceDesc = grpc.ServiceDesc{
	ServiceName: "UrlShortener",
	HandlerType: (*UrlShortenerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _UrlShortener_Create_Handler,
		},
		{
			MethodName: "GetOriginalUrl",
			Handler:    _UrlShortener_GetOriginalUrl_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetStatistic",
			Handler:       _UrlShortener_GetStatistic_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "urlShortener.proto",
}
